language: go
go: "1.10"
jobs:
  include:
    - stage: test
      install: go get github.com/projectriff/riff
      script: make test verify-docs
    - stage: publish
      sudo: required
      services:
      - docker
      script: ./.travis.docker-push.sh
    - stage: fats
      script: "curl -s -L https://github.com/projectriff/fats/raw/master/.travis.fats-trigger.sh | bash"
stages:
  - test
  - name: publish
    if: branch = master AND type = push
  - name: fats
    if: branch = master AND type = push
